# Generated by Django 4.2.1 on 2023-10-03 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 3, 8, 57, 40, 880684)),
        ),
    ]
