# Generated by Django 4.2.1 on 2023-10-03 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 3, 10, 37, 14, 171440)),
        ),
    ]
