# Generated by Django 4.2.1 on 2023-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_request_message_alter_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.CharField(max_length=200),
        ),
    ]
